### ISSUE TITLE
Compatibility with Pynq-Z2

### ISSUE THREAD

**Issue by Sellto** [Xilinx/DPU-PYNQ#22]
Hello
I could see that vitis ai 1.3 was available and I saw in an issue that it was a constraint to have pynq-DPU which would be compatible with the Z2. Can you estimate the release date of a version for the pynq Z2?

**Comment by Sellto** [comment]
No news?

**Comment by yunqu** [comment]
@Sellto  We are still working on the aarch64 but we hope we will kick off armv7l support very soon.

**Comment by yunqu** [comment]
There are some issues with support on zynq 7000. Vitis AI 1.3.1 will support Zynq 7000 so we will wait on that release to update our repo.

**Comment by yunqu** [comment]
We have internally Zynq7000 support. However, at this point due to lack of man power to support it, we will not release it publicly. The basic steps are similar to Zynq Ultrascale, since all the source code is available on Vitis AI git. If you still need it I can send over a private compiled VART library tarball; and as a matter of fact, that could be compiled by users by themselves as well.

**Comment by chebro** [comment]
> If you still need it I can send over a private compiled VART library tarball; and as a matter of fact, that could be compiled by users by themselves as well.

could you please point to the instructions to compile and run pynq-dpu on the pynq z2?
